name: ape-v2-base-strategy-adapter

plugins:
  - name: solidity
  - name: etherscan
  - name: hardhat
  - name: infura
  - name: vyper

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    ref: 4.7.1
  - name: yearnV2
    github: yearn/yearn-vaults
    ref: v0.4.6
  - name: tokenized-strategy
    github: yearn/tokenized-strategy
    ref: v3.0.1
    contracts_folder: src
    exclude:
     - src/test/**/*

solidity:
  version: 0.8.18
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.7.1"
    - "@yearnV2=yearnV2/v0.4.6"
    - "@tokenized-strategy=tokenized-strategy/v3.0.1"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura